## Columbia University
### ECBM E4040 Neural Networks and Deep Learning. Fall 2019.

# ECBM E4040 - Assignment 0 
## This jupyter notebook has TensorFlow 2.0 examples (as opposed to TF1.13)
## This version of assignment will be distributed later in semester

<p style='color:red'>To run this notebook install Tensorflow 2.0 in a new virtual environment (suggested name envTF20. Use `pip install tensorflow==2.0.0-rc1` or `pip install tensorflow-gpu==2.0.0-rc1` accordingly</p>

Welcome to ECBM E4040 Neural Networks & Deep Learning. 

Deep learning is very popular nowadays both in academia and in industry. In this course, we'll teach you the concepts of neural networks, and how to program your own neural network. 

The __assignment 0__ is meant to help you get accustomed to the programming environment we use for this course. It consists of 4 parts:
* Programming environment setup - Google Compute Engine/local machine, Python, TensorFlow.
* How to use Jupyter Notebook
* TensorFlow basics
* A demo of TensorFlow program

<p style='color:red'>The things marked with <strong>'TODO'</strong> requires you to finish.</p>

If you have trouble, feel free to contact TAs or post your problem on Piazza.

Good luck!

## Part 1 - Environment setup

For the course, we use __Python__ as our programming language, and [__TensorFlow__](https://www.tensorflow.org) as the deep learning framework. Before we start having fun with deep learning, we need to equip ourselves with some knowledge.

Our [course website](https://ecbm4040.bitbucket.io) provides a number of tutorials including:
1. Python tutorial
2. Google Compute Engine setup
3. Local environment setup
4. Linux tutorial
5. Git commands
6. TensorFlow tutorial

<p style='color:red'><strong>TODO:</strong></p>
1. Follow the 2nd tutorial to set up your Google Compute Engine VM instance.
2. Follow the 3rd tutorial to set up your local deep learning environemnt. Since using Google Cloud cost you money, we recommend that you debug your code locally and run it remotely.
3. Depending on your understanding of Python, Linux, Git and TensorFlow, the rest tutorials are optional.

You may encounter various problems in this part. Don't hesitate to ask for help.

After you set up your environment, clone the assignment repo to your VM instance and start working.

## Part 2 - How to use Jupyter Notebook

Jupyter Notebook is an interactive Python programming interface. Jupyter Notebook files have a postfix _.ipynb_, and each file is made up of several blocks of code, which we call __cells__. Each cell can be configured as __coding cell__ or __Markdown text cell__. 

A few basic instructions:

* The menu bars are located on the top of a notebook.
* To execute a cell, select it, and press `ctrl+Enter`. (You may also try `shift+Enter` and `alt+Enter` to see the difference).
* To switch between code and Markdown, select a cell, and select the mode you want in the dropdown menu in the menu bar.

A full guide to Jupyter Notebook can be accessed in the _Help_ menu in the menu bar.


In [1]:
# To test that you've understood how to use it, make this cell output a string 'Hello Jpuyter!'. 
# We've written the code, all you need to do is to execute it.
print('Hello Jupyter!')

Hello Jupyter!


## Part 3 - TensorFlow Basics

TensorFlow is one of the most popular deep learning frameworks now in the world. Originally created by Google, it has received a lot of community support. In this part, we're going to look at some basic TensorFlow concepts and operations, so that you can start playing with it.

TensorFlow 2.0 focuses on simplicity and ease of use, with updates like eager execution, intuitive higher-level APIs, and flexible model building on any platform

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


# Import the TensorFlow module
import tensorflow as tf
# The following modules will be used in Part 3 and 4
# Make sure you install the latest version of numpy and matploblib.
# If not, try "conda install numpy" and "conda install matploblib" in the console (the one you used to control your VM)
# And restart the notebook. 
import numpy as np
%matplotlib inline
from matplotlib import pyplot as plt
import time

#### 1. Use of session

In tensorflow 2.0 the concept of sessions has ben deprecated. Now variable are accessible instantly as compared to after sess.run making it more pythonic. This mode of using TensorFlow is called Eager Evaluation.

In [4]:
# By TensorFlow official website, "A Session instance encapsulates the environment in which Operations
# in a Graph are executed to compute Tensors." In short, this is where the computation happens.

# Define a string constant
string = tf.constant('Hello TensorFlow!')
print(string.numpy())

#############################################################################
#                                                                           #
#                            TENSORFLOW 1.x                                 #
#                                                                           #
#############################################################################
# # There are 2 ways of using a session. 
# # First one:
# sess = tf.Session()
# print(sess.run(string))
# sess.close()

# # Second one:
# with tf.Session() as sess:
#     print(sess.run(string))
    
# The session doesn't close automatically, so you need to do it manually, otherwise you'll have resource error sometimes.
# We recommend the second way because we sometimes forget to put sess.close() at the end of our program.

Tensor("Const_1:0", shape=(), dtype=string)


<p style='color:red'><strong>TODO:</strong></p>

In [5]:
# Follow the example above, use TensorFlow to output the string 'YOUR_NAME:YOUR_UNI'. 
# YOUR CODE HERE
string = tf.constant("Deepak: dr2998")
print(string.numpy())

Tensor("Const_2:0", shape=(), dtype=string)


#### 2. Two phases of tensorflow 



In [5]:
# Due to Eager Evaluation mode, tensors can be accesed immediately after creation, thus you do not need to create a computation
# graph and then run it.

x = tf.random.normal([5,5]) # create a 5*5 matrix filled with random values from standard normal distribution
y = tf.random.normal([5,5])
z = tf.matmul(x,y) # do matrix multiplication


print("Value of z :")
print(z) 

print("\n")


#############################################################################
#                                                                           #
#                            TENSORFLOW 1.x                                 #
#                                                                           #
#############################################################################
#the second Phase mentioned below is not required in tf2.0
# # Second phase, use session to execute the operations defined in the graph:
# # After this, we can get the actual numeric value of z.
# with tf.Session() as sess:
#     z_val = sess.run(z)
# print("Value of z after calling session.run():")
# print(z_val)

Value of z :
tf.Tensor(
[[ 2.2086558   0.9775742   0.6091891   2.5402653   2.2629886 ]
 [-3.1174679  -1.854012   -0.19275923 -2.722007   -3.716808  ]
 [ 2.007538   -0.2849345  -0.48070514  0.6085319  -2.0005276 ]
 [-4.229974   -0.5399788  -0.561396   -1.7189919  -3.595109  ]
 [ 1.7079922  -0.04789529 -0.95289195  1.202655   -5.289135  ]], shape=(5, 5), dtype=float32)




#### 3. Basic math

In [6]:
# Since TensorBoard can used to visualize your models, naming your nodes is good programming practise.
# Define 2 constant nodes. All operations are encapsulated within tf.Tensor

a = tf.constant(7, dtype=tf.float32, name='a')
b = tf.constant(10, dtype=tf.float32, name='b')

# Addition and subtraction
add = tf.add(a, b, name='add') # same as a+b
sub = tf.subtract(a, b, name='sub') # same as a-b

# No need for the session to run these operations
print(a) 
print(b) 
print(add)
print(sub) 

[<tf.Tensor: id=18, shape=(), dtype=float32, numpy=7.0>, <tf.Tensor: id=19, shape=(), dtype=float32, numpy=10.0>, <tf.Tensor: id=20, shape=(), dtype=float32, numpy=17.0>, <tf.Tensor: id=21, shape=(), dtype=float32, numpy=-3.0>]


<p style='color:red'><strong>TODO:</strong></p>

In [8]:
# Visit https://www.tensorflow.org/api_guides/python/math_ops, 
# find proper operations to calcualte a*b (multiplication), a/b (division), a^b (power) and log(a) (natural logarithm),
# and demonstrate their uses by outputing their results in a session. (Note: 'a' and 'b' are defined in the previous cell, you
# should use them directly.)

# YOUR CODE HERE

mul = tf.multiply(a, b, name='multiplication')
div = tf.divide(a, b, name='div')
power = tf.pow(a, b, name='power')
log = tf.math.log(a, name='log')

print(mul)
print(div)
print(power)
print(log)

[<tf.Tensor: id=29, shape=(), dtype=float32, numpy=70.0>, <tf.Tensor: id=30, shape=(), dtype=float32, numpy=0.7>, <tf.Tensor: id=31, shape=(), dtype=float32, numpy=282475260.0>, <tf.Tensor: id=32, shape=(), dtype=float32, numpy=1.9459101>]


#### 4. Constant tensor, sequences and random numbers

In [10]:
# In TensorFlow, a tensor is an n-dimensional array. 
# Thus, a 0-d tensor is a scalar. 1-d tensor is a vector, and so on.

# We can use TF functions to create all-zero and all-one tensors.
zero_array = tf.zeros(shape=[2,3], dtype=tf.float32, name='zero_array')
one_array = tf.ones(shape=[2,3], dtype=tf.float32, name='one_array')

# Or use a template to infer the shape.
template = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32, name='template') # Has [2,3] shape
zero_like = tf.zeros_like(template, name='zero_like')
one_like = tf.ones_like(template, name='one_like')

# Some sequence generating functions
lin_seq = tf.linspace(start=0.0, stop=5.0, num=5, name='lin_seq')
lin_range = tf.range(start=0, limit=7, delta=1, name='lin_range')

# A random number function
norm = tf.random.normal(shape=[5], mean=3, stddev=2.0)


print('0 array:\n', zero_array)
print('1 array:\n', one_array)
print('0 inferred:\n', zero_like)
print('1 inferred:\n', one_like)
print('linear sequence:\n', lin_seq)
print('range:\n', lin_range)
print('Random normal:\n', norm)

0 array: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
1 array: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
0 inferred: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
1 inferred: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
linear sequence: tf.Tensor([0.   1.25 2.5  3.75 5.  ], shape=(5,), dtype=float32)
range:  tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
Random normal: tf.Tensor([3.9591546 4.698679  1.4101083 6.180681  4.6036777], shape=(5,), dtype=float32)


<p style='color:red'><strong>TODO:</strong></p>

In [11]:
# 1: Generate a 3*3 matrix filled with 9s. 
# 2: Generate a sequence start from -5.0 to 5.0(inclusive), with step size of 1.0.
# 3: Generate another 3*3 matrix with normal distribution. Choose any mean and stddev you like.
# Hint: Visit https://www.tensorflow.org/api_guides/python/constant_op

# YOUR CODE HERE
nine_array = tf.ones(shape=[3, 3], dtype=tf.float32, name='one_array') * 9
seq = tf.range(-5.0, 6.0, delta=1.0, name='lin_range')
dist = tf.random.normal(shape=[3, 3], mean=0.0, stddev=1.0, dtype=tf.float32, name='normal_distribution')


print('nine array:\n',nine_array)
print('sequence:\n', seq)
print('distribution:\n',dist)


nine array:
 tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]], shape=(3, 3), dtype=float32)
sequence:
 tf.Tensor([-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.], shape=(11,), dtype=float32)
distribution:
 tf.Tensor(
[[-0.91352344  0.5955544   0.3669424 ]
 [-0.18652268  0.6424556  -0.6187372 ]
 [-1.3065095   1.0197403   0.64522904]], shape=(3, 3), dtype=float32)


#### 5. Variables

In [12]:
# So far, what we've defined are constants, i.e. their values can't be changed. With TensorFlow variables, you can update 
# values now during training of a network.

x = tf.Variable([2,3], dtype=tf.float32) # You need to give an initial value to the variable.

# Several ops we can use to change the value of the variable. Note that they all become nodes in the graph.
assign = x.assign([4,5])
print(assign)
add = x.assign_add([1,1])
print(add)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 5.], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([5., 6.], dtype=float32)>


<p style='color:red'><strong>TODO:</strong></p>

In [13]:
# Create a 3*3 tensor variable (the initial values don't matter), then assign values from 1 to 9 to it.
# We need to see the initial values and the new values after the assign op to give you full points.
# YOUR CODE HERE

x = tf.Variable(tf.ones(shape=[3,3], dtype=tf.float32),dtype=tf.float32)
print(x)

assign = x.assign([[1,2,3],[4,5,6],[7,8,9]])
print(assign)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>


#### 6. Placeholders (DEPRECATED FOR EAGER EXECUTION)

In [14]:
## IMPORTANT : PLACEHOLDERSS ARE NO LONGER NEEDED IN TF2.0 as there is no need for feed dicts anymore

#############################################################################
#                                                                           #
#                            TENSORFLOW 1.x                                 #
#                                                                           #
#############################################################################

# # When you want to feed your data into the network, an intuitive way is to put your data in tf.constant. But that's not clever.
# # We have placeholders to hold your data. The use is very easy.

# # Define a placeholder
# y = tf.placeholder(shape=[5,], dtype=tf.float32) # [5,] or [5] means this is an 1-d array of size 5.
# z = tf.placeholder(shape=[None, 5], dtype=tf.float32) # Use None in a dimension means any size is acceptable.
# y_plus = y + 1
# z_minus = z - 1

# # Then generate some real arrays to feed into the placeholders
# feed_y = np.array([1,1,1,1,1], dtype=np.float32) 
# feed_z = np.random.uniform(size=[2,5])

# # Now use a dictionary to feed the true values into the placeholders.
# # TensorFlow will detect that the ops we run is linked to some placeholders which need to be fed.
# with tf.Session() as sess:
#     print(sess.run([y_plus,z_minus], feed_dict={y: feed_y, z:feed_z}))

#### 7. Scope and variable reuse (Deprecated)

In [16]:
# IMPORTANT: Variable scopes have been deprecated in tf 2.0.
#instead of using tf.get_variable any variable not kept track of will be garbage collected like regular python variable

#############################################################################
#                                                                           #
#                            TENSORFLOW 1.x                                 #
#                                                                           #
#############################################################################


# # Define a variable scope
# with tf.variable_scope('v_scope'):
#     # use tf.get_variable() to create a variable 'x' under scope 'v_scope'
#     init = tf.constant_initializer([1.0,2.0,3.0,4.0,5.0,6.0]) # define the initial method
#     x = tf.get_variable(name='x',shape=[2,3],dtype=tf.float32,initializer=init,use_resource=False)
#     print(x)
#     print(x.name)

#### 9. Data type impact

In [28]:
# In tensorflow, float type of data includes float32 and float64. Remember that in your later implementation, 
# you should always consider float32 as your first choice for sake of efficiency, even though it will lose precision.
# Here we are going to compare the precision difference between these two types.

A32 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float32)
B32 = (A32 + 0.1)**2
A64 = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.float64)
B64 = (A64 + 0.1)**2


print('float32 result: \n {}'.format(B32))
print('float64 result: \n {}'.format(B64))

float32 result: 
 [[ 1.21       4.4099994  9.61     ]
 [16.81      26.009998  37.21     ]]
float64 result: 
 [[ 1.21  4.41  9.61]
 [16.81 26.01 37.21]]


We've introduced basic TensorFlow operations and concepts. Now, we recommend you to visit the TensorFlow tutorial link provided. It will help you a lot, as the operations we introduced is not sufficient for building a neural network yet.